import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  login: {
    fontSize: 30,
    fontFamily: 'The_Jamsil_3',
  },
  IdInput: {
    width: 200,
    height: 50,
    borderWidth: 1,
    borderColor: 'gray',
    backgroundColor: 'white',
    borderRadius: 10,
    marginTop: 20,
    fontSize: 15,
    paddingHorizontal: 20,
    fontFamily: 'The_Jamsil_3',
  },
  TextInput: {
    width: 300,
    height: 50,
    borderWidth: 1,
    borderColor: 'gray',
    backgroundColor: 'white',
    borderRadius: 10,
    marginTop: 10,
    fontSize: 15,
    color: 'black',
    fontFamily: 'The_Jamsil_3',
    paddingHorizontal: 20,
  },
  doubleCheck: {
    width: 100,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    marginTop: 20,
    marginLeft: 5,
    borderRadius: 5,
  },
  button: {
    width: 100,
    height: 40,
    borderWidth: 1,
    borderColor: '#007AFF',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    marginTop: 20,
    marginBottom: 20,
    borderRadius: 5,
  },
  select: {
    borderWidth: 1,
    width: 150,
    height: 40,
    marginTop: 10,
    borderColor: 'gray',
    backgroundColor: 'white',
    marginLeft: 2.5,
    borderRadius: 5,
    paddingHorizontal: 20,
    paddingVertical: 20,
    fontFamily: 'The_Jamsil_3',
  },
});

export const pickerSelectCity = StyleSheet.create({
  inputIOS: {
    marginTop: 10,
    fontSize: 16,
    height: 50,
    width: 150,
    borderColor: 'gray',
    backgroundColor: 'white',
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
    marginLeft: 3,
    color: 'black',
    fontFamily: 'The_Jamsil_3',
  },
  inputAndroid: {
    marginTop: 10,
    fontSize: 16,
    height: 50,
    width: 150,
    borderColor: 'gray',
    backgroundColor: 'white',
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
    color: 'black',
    fontFamily: 'The_Jamsil_3',
  },
});

export const pickerSelecFamily = StyleSheet.create({
  inputIOS: {
    marginTop: 20,
    fontSize: 16,
    height: 50,
    width: 300,
    borderColor: 'gray',
    backgroundColor: 'white',
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
    color: 'black',
    fontFamily: 'The_Jamsil_3',
  },
  inputAndroid: {
    marginTop: 10,
    fontSize: 16,
    height: 50,
    width: 300,
    borderColor: 'gray',
    backgroundColor: 'white',
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
    color: 'black',
    fontFamily: 'The_Jamsil_3',
  },
});
